In [14]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import pandas as pd


In [3]:
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 0])
clf = Perceptron()
clf.fit(X, y)
predictions = clf.predict(X)

C:\Users\PythonCode\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:144: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [5]:
predictions

array([0, 0, 0])

In [6]:
y_true = np.array([1,0,0])

In [7]:
accuracy_score(y_true, predictions)

0.6666666666666666

In [9]:
scaler = StandardScaler()
X_train = np.array([[100.0, 2.0], [50.0, 4.0], [70.0, 6.0]])
X_test = np.array([[90.0, 1], [40.0, 3], [60.0, 4]])
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
X_train

array([[100.,   2.],
       [ 50.,   4.],
       [ 70.,   6.]])

In [11]:
X_train_scaled

array([[ 1.29777137, -1.22474487],
       [-1.13554995,  0.        ],
       [-0.16222142,  1.22474487]])

In [12]:
X_test

array([[90.,  1.],
       [40.,  3.],
       [60.,  4.]])

In [13]:
X_test_scaled

array([[ 0.81110711, -1.83711731],
       [-1.62221421, -0.61237244],
       [-0.64888568,  0.        ]])

In [19]:
df_train = pd.read_csv('perceptron-train.csv', names = ['Target','Feature1','Feature2'])
df_train.head()
Y_train = df_train['Target']
X_train = df_train[['Feature1', 'Feature2']]

df_test = pd.read_csv('perceptron-test.csv', names = ['Target','Feature1','Feature2'])
df_test.head()
Y_test = df_test['Target']
X_test = df_test[['Feature1', 'Feature2']]

In [31]:
clf = Perceptron(random_state=241)
clf.fit(X_train, Y_train)
predictions = clf.predict(X_test)
Wo_Scaling_Acc = accuracy_score(Y_test, predictions)

C:\Users\PythonCode\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:144: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


## Normalize

In [30]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [32]:
clf_scaled = Perceptron(random_state=241)
clf_scaled.fit(X_train_scaled, Y_train)
Scaling_Acc = accuracy_score(Y_test, clf_scaled.predict(X_test_scaled))

C:\Users\PythonCode\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:144: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [33]:
d = Scaling_Acc - Wo_Scaling_Acc

In [34]:
d

0.18999999999999995

In [35]:
Scaling_Acc

0.845

In [38]:
d.round(5)

0.19